# This workflow will build and test a .NET project
name: .NET Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Setup internal nuget source
      run: dotnet nuget add source --username thenameless314159 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name opendofus2 "https://nuget.pkg.github.com/opendofus2/index.json"
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
